include $(TOPDIR)/rules.mk

LUCI_TITLE:=Advanced Hybrid Firewall Status and Rules View
LUCI_DEPENDS:=+luci-app-firewall +luci-base

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
